### PR TITLE
Adding related work section

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@sankhesh @alvarosan any suggestions?

**Comment by sankhesh** [comment]
@aashish24 This branch does not compile as is because of the some of the new references in the bibliography. I usually update the Zotero library and just export a properly formatted bib file from there.  

Mind if I add these references to the Zotero library and update the bib file on this branch?

**Comment by aashish24** [comment]
@sankhesh absolutely! Push it here.

**Comment by aashish24** [comment]
@sankhesh looks like I over-ride your changes. Can you push your change again? Sorry about that.

**Comment by aashish24** [comment]
thanks @sankhesh

**Pull request merged**
