### PR TITLE
Final changes

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@sankhesh @alvarosan as promised. Here is my final changes to the paper. 

@sankhesh please remember that we may have combined images in order to only have 10 images as allowed.

**Comment by aashish24** [comment]
@sankhesh I think we have only these left for now: 

1. Add class diagram and 1-2 lines on it in the text
2. Update vtk pipeline diagram
3. Format so that we only have 10 pages and 10 figures? 
4. Add one-to-two para on domain applications

**Comment by sankhesh** [comment]
Thanks @aashish24. I'll get to it later today 🤞

**Comment by aashish24** [comment]
thanks @sankhesh can you approve my branch?

**Comment by sankhesh** [comment]
LGTM

**Pull request merged**
